name: shellcheck

on:
  pull_request:
    branches: [main, develop]
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: '.'
          pattern: '*.sh'
          level: error
          fail_level: error
